### ISSUE TITLE
col will overflow row

### ISSUE THREAD

**Issue by guyskk** [xcatliu/mobi.css#26]
col and the pre element will overflow row

```
<body>
    <div class="flex-center">
        <div class="container">
            <nav>
                <button class="btn" type="button" name="button">Header</button>
            </nav>
            <div class="row">
                <div class="col-1-4 hide-on-mobile" style="padding:0 30px;">
                    <p>Scan to view on mobile</p>
                    <img src="path/to/qrcode.png" />
                </div>
                <div class="col">
<pre>Mobi.cssMobi.cssMobi.cssMobi.cssMobi.cssMobi.cssMobi.cssMobi.cssMobi.cssMobi</pre>
                </div>
            </div>
        </div>
    </div>
</body>
```

**Comment by guyskk** [comment]
![selection_001](https://cloud.githubusercontent.com/assets/6367792/18237444/073e174a-7321-11e6-9a73-e7b7b61c7399.png)

**Comment by xcatliu** [comment]
@guyskk I tried to solve it, and then find two solutions.

We can provides two more classes, `col-2-3`, `col-3-4`, then use `col-1-4` and `col-3-4`, everything goes well. But if you still use `col-1-4` and `col`, the problem still exists.

![image](https://cloud.githubusercontent.com/assets/5453359/18239528/74a855be-7378-11e6-8afe-840b0c6f4576.png)

Or we can set the `flex-wrap` of `row` to `wrap`, then `col` with `pre` inside will be wrapped to the second line.

![image](https://cloud.githubusercontent.com/assets/5453359/18239558/96242d08-7378-11e6-9559-f1348239e8d5.png)

I prefer the first choice, since I replied in #18, I don't want to row to be wrap-able.

http://v4-alpha.getbootstrap.com/layout/flexbox-grid/
http://flexboxgrid.com/
